# -*- coding: utf-8 -*-
"""
/***************************************************************************
 frms_downloader
                                 A QGIS plugin
 This plugin to download FMRS Map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-04-21
        copyright            : (C) 2020 by IFEE
        email                : nguyenvanthi@ifee.edu.vn
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load frms_downloader class from file frms_downloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .frms_downloader import frms_downloader
    return frms_downloader(iface)
